/*
 * The Clear BSD License
 * Copyright 2017-2018 NXP
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted (subject to the limitations in the disclaimer below) provided
 *  that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PTG7 (number 50), D4[3]/PTG7_BLUE
  @{ */
#define BOARD_INITLEDS_LED_BLUE_GPIO GPIOB            /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITLEDS_LED_BLUE_GPIO_PORT kGPIO_PORTG /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITLEDS_LED_BLUE_PORT PORTG            /*!<@brief PORT device name: PORTG */
#define BOARD_INITLEDS_LED_BLUE_PIN 7U                /*!<@brief PORTG pin index: 7 */
                                                      /* @} */

/*! @name PTG6 (number 51), D4[4]/PTG6_GREEN
  @{ */
#define BOARD_INITLEDS_LED_GREEN_GPIO GPIOB            /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITLEDS_LED_GREEN_GPIO_PORT kGPIO_PORTG /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITLEDS_LED_GREEN_PORT PORTG            /*!<@brief PORT device name: PORTG */
#define BOARD_INITLEDS_LED_GREEN_PIN 6U                /*!<@brief PORTG pin index: 6 */
                                                       /* @} */

/*! @name PTG5 (number 52), D4[1]/PTG5_RED
  @{ */
#define BOARD_INITLEDS_LED_RED_GPIO GPIOB            /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITLEDS_LED_RED_GPIO_PORT kGPIO_PORTG /*!<@brief PORTB GPIO port: PORTB */
#define BOARD_INITLEDS_LED_RED_PORT PORTG            /*!<@brief PORT device name: PORTG */
#define BOARD_INITLEDS_LED_RED_PIN 5U                /*!<@brief PORTG pin index: 5 */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDs(void);

/*! @name UART1_RX (number 64), J1[3]/PTC6_RXD1/UART1_RX_TGTMCU
  @{ */
/* @} */

/*! @name UART1_TX (number 63), J1[1]/PTC7_TXD1/UART1_TX_TGTMCU
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void);

/*! @name I2C0_SCL (number 59), J2[20]/PTA3_ACCEL_SCL
  @{ */
/* @} */

/*! @name I2C0_SDA (number 60), J2[18]/PTA2_ACCEL_SDA
  @{ */
/* @} */

/*! @name PTD4 (number 56), PTD4_ACCEL_INT1
  @{ */
#define BOARD_INITACCEL_ACCEL_INT1_GPIO GPIOA            /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITACCEL_ACCEL_INT1_GPIO_PORT kGPIO_PORTD /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITACCEL_ACCEL_INT1_PORT PORTD            /*!<@brief PORT device name: PORTD */
#define BOARD_INITACCEL_ACCEL_INT1_PIN 4U                /*!<@brief PORTD pin index: 4 */
                                                         /* @} */

/*! @name PTD3 (number 57), PTD3_ACCEL_INT2
  @{ */
#define BOARD_INITACCEL_ACCEL_INT2_GPIO GPIOA            /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITACCEL_ACCEL_INT2_GPIO_PORT kGPIO_PORTD /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITACCEL_ACCEL_INT2_PORT PORTD            /*!<@brief PORT device name: PORTD */
#define BOARD_INITACCEL_ACCEL_INT2_PIN 3U                /*!<@brief PORTD pin index: 3 */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCEL(void);

/*! @name EXTAL (number 13), EXTAL
  @{ */
/* @} */

/*! @name XTAL (number 14), XTAL
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSC(void);

/*! @name CAN0_TX (number 6), J5[5]/U7[1]/PTE7_CONN/CAN_TX
  @{ */
/* @} */

/*! @name CAN0_RX (number 7), J5[4]/U7[4]/PTH2_CONN/CAN_RX
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCAN(void);

/*! @name PTB1 (number 41), J1[4]/PTB1_IRTX
  @{ */
#define BOARD_INITINFRARED_IRTX_GPIO GPIOA            /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITINFRARED_IRTX_GPIO_PORT kGPIO_PORTB /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITINFRARED_IRTX_PORT PORTB            /*!<@brief PORT device name: PORTB */
#define BOARD_INITINFRARED_IRTX_PIN 1U                /*!<@brief PORTB pin index: 1 */
                                                      /* @} */

/*! @name PTA1 (number 61), J1[10]/PTA1_D4_T1/PTA1_IRRX
  @{ */
#define BOARD_INITINFRARED_IRRX_GPIO GPIOA            /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITINFRARED_IRRX_GPIO_PORT kGPIO_PORTA /*!<@brief PORTA GPIO port: PORTA */
#define BOARD_INITINFRARED_IRRX_PORT PORTA            /*!<@brief PORT device name: PORTA */
#define BOARD_INITINFRARED_IRRX_PIN 1U                /*!<@brief PORTA pin index: 1 */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitINFRARED(void);

/*! @name ADC0_SE12 (number 38), PTF4_THER
  @{ */
/* @} */

/*! @name ADC0_SE13 (number 37), PTF5_THER
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTHER(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
